name: Latihan Pertama
on:
 workflow_dispatch:
 schedule:
   - cron: "*/2 * * * *"
jobs:
  run-python:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: Setup Python
       uses: actions/setup-python@v5
       with:
         python-version: "3.11"

     - name: Run Python Script
       run: python main.py


   
